### ISSUE TITLE
spmat installs a buggy Cython version

### ISSUE THREAD

**Issue by k-simpson** [ihmeuw-msca/spmat#15]
FHS is experiencing widespread build failures today due to spmat installing a version of Cython with a known bug (3.0.4) ([Github](https://github.com/cython/cython/issues/5771)). We don’t use spmat directly, but indirectly through flme ([Github](https://github.com/ihmeuw-msca/lme-for-forecast/blob/v0.1.0/pyproject.toml#L14)). Our issue can be reproduced with the following:
```
git clone https://github.com/ihmeuw-msca/spmat.git
cd spmat
conda create -n spmat python=3.10 "pip>=21.1" --yes
conda activate spmat
python -m pip install .[dev] --upgrade pip
```

I have been able to resolve the issue by constraining the Cython version to Cython<=3.0.3 here in the pyproject.toml ([Github](https://github.com/ihmeuw-msca/spmat/blob/v0.0.9/pyproject.toml)). I’d push the change to the repo myself but I don’t have permission to do so on Github.

If it’s decided that there will be a new version of spmat to resolve this issue, we will then also need a new version of flme because it hard-pins to spmat==0.0.9 ([Github](https://github.com/ihmeuw-msca/lme-for-forecast/blob/v0.1.0/pyproject.toml#L14)).

So far we have been unable to resolve this Cython version issue ourselves by installing older versions into our environments before installing spmat, and we are not able to simply wait for the Cython developers to fix version 3.0.4.

**Comment by zhengp0** [comment]
Thanks Kyle! I believe it has been resolved in #16
